### ISSUE TITLE
Property 'state' of type '{ [key: string]: MappingType; } | undefined' is not assignable to string index type 'string | number | MappingType'

### ISSUE THREAD

**Issue by germanp173** [eva-design/eva#12]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report

### Issue description

**Current behavior:**
I'm attempting to use `react-native-ui-kitten` which uses `@eva-design/eva` and after I follow the setup instructions from [here](https://akveo.github.io/react-native-ui-kitten/docs/guides/add-into-existing-project#configure-application-root), my typescript build now fails due to a compilation error in `schema.d.ts`:

![Capture](https://user-images.githubusercontent.com/38846104/59746041-e03ebb00-922a-11e9-9406-41dc45055580.PNG)

As a workaround, anyone using UI Kitten/Eva-Design with Typescript will have to toggle the `skipLibCheck` flag to `true` in their `tsconfig.json`.

**Expected behavior:**
Importing `@eva-design/eva` should not break a tsc build

**Steps to reproduce:**

1. Initialize a new react native typescript application by running `react-native init TempApp --template typescript` (assuming you have the react-native cli installed)
2. Follow the `react-native-ui-kitten` setup instructions from [here](https://akveo.github.io/react-native-ui-kitten/docs/guides/add-into-existing-project#add-into-existing-project)
3. Run `tsc -p ./tsconfig.json` to execute the typescript build

### Other information:

**Package versions**
```
@eva-design/eva: 1.0.0
react: 16.8.3
react-native: 0.59.8
react-native-ui-kitten: 4.0.1
```

**Comment by malashkevich** [comment]
Hello @germanp173. Thanks for reporting this issue.
You are right as a workaround you can use `skipLibCheck`. Currently, we are working on a solution for this bug.

**Comment by 32penkin** [comment]
Hello @germanp173! Thank you for letting us know about such issues. Please try to update 'react-native-ui-kitten'  package to the 4.0.3 version. I guess it was fixed in this release.

**Comment by artyorsh** [comment]
Hi @germanp173 
The title of your issue differs from the error displayed on a screenshot
Please give any feedback if updating to UI Kitten 4.0.3 was helpful for you. 4.0.3 fixes the problem described on a screenshot, not that one you've described in issue title

**Comment by artyorsh** [comment]
Hi @germanp173 
The title of your issue differs from the error displayed on a screenshot
Please give any feedback if updating to UI Kitten 4.0.3 was helpful for you. 4.0.3 fixes the problem described on a screenshot, not that one you've described in issue title

**Comment by germanp173** [comment]
@32penkin My apologies, my screenshot might have been misleading since it also included a bug that's specific to `react-native-ui-kitten` which was indeed fixed with version 4.0.3 (verified it myself).

The bug that's specified in the title of this issue and the first error shown in the screenshot is still present since it's specific to `@eva-design`.

Below is a screenshot of a tsc build with `react-native-ui-kitten` version 4.0.3. 

![image](https://user-images.githubusercontent.com/38846104/59980641-939e0b80-95ad-11e9-9006-c15cffbfff25.png)

Due to this issue, folks using typescript with `react-native-ui-kitten` version 4.0.3 and `@eva-design` will still need to set the `skipLibCheck` flag to true in `tsconfig.json`.

**Comment by artyorsh** [comment]
This one will also be fixed in future releases. Thanks for the details

**Comment by germanp173** [comment]
Great thanks for the support!

**Comment by artyorsh** [comment]
@germanp173 
Can you please provide an example code which causes this compile error? Thanks

**Comment by germanp173** [comment]
Sure, take a look at [EvaIssue12Example](https://github.com/germanp173/EvaIssue12Example).

All I did was:
1. Initialize a react native typescript app using the latest react native CLI (version 2.01)
1. Add and configure UI Kitten with Eva Design as specified [here](https://akveo.github.io/react-native-ui-kitten/docs/guides/install-ui-kitten#create-a-new-project)

From this repo, you can run `npm run build` to reproduce the problem. I also included the `skipLibCheck` flag in the `tsconfig.json` which you can toggle to work around the problem.

Let me know if you need anything else.

**Comment by artyorsh** [comment]
@germanp173 This is fixed. You can get rid of this warnings with updating `react-native-ui-kitten` package to v4.0.5 and `@eva-design/eva` to v1.0.1 🔥

**Comment by germanp173** [comment]
@artyorsh New versions work like a charm and I was able to remove that flag. Thanks again for your quick support! 💯
